[package]
name = "iced_poc"
version = "0.1.0"
authors = ["TuntematonSotilas"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.64"
web-sys = { version = "0.3.41", features = [ "console" ] }